version: "4.0"
services:
  mock:
    image: mockserver/mockserver
    ports:
    - "1080:1080"
    environment:
    - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/init.json
    volumes:
    - ./src/main/resources/init.json:/config/init.json
    