version: '4.0'
services:
  mongo:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    volumes:
     - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
     
     