version: '4.0'
services:
  mongo:
   image: mongo
   environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=root
#   ports:
#   - "27017:27017"
   volumes:
   - "./data:/docker-entrypoint-initdb.d"
  employee-service:
   image: emp
   build: ../docker-employee-microservice
   deploy:
    replicas: 2
   depends_on:
   - mongo
   environment:
   - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/admin
  animal-service:
   image: animal
   build: ../docker-animal-microservice
   deploy:
    replicas: 2
   depends_on:
   - mongo
   - employee-service
   environment:
   - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/admin
   - emp-service-url=employee-service:9090/employee
  nginx:
   image: nginx
   depends_on:
   - employee-service
   - animal-service
   ports:	
   - "80:80"
   volumes:
   - "./conf/nginx.conf:/etc/nginx/nginx.conf"